### ISSUE TITLE
Permissions Error 

### ISSUE THREAD

**Issue by OmarElgammal1** [elmezianech/SageMaker-IT-Domain-Expert#1]
@elmezianech I get an error that I think mainly is because there are missing permissions that I can't find in the current version of AWS.
This is the image from the course:
![image](https://github.com/user-attachments/assets/3ef29278-d939-46c2-9f9c-7490170bb6d2)
These are the permissions found now:
![image](https://github.com/user-attachments/assets/8a00ac36-4e69-44f0-9d7a-c7ebe9f23e85)
I can't find "manage endpoints" and "manage experiments" permissions. do you know what should I do about it?

**Comment by elmezianech** [comment]
Actually i submitted my project about 4 months ago, and as i still remember i found the permissions as described in the image from the course.

**Comment by OmarElgammal1** [comment]
Okay thank you @elmezianech
